# Generated by Django 5.2 on 2025-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial_squashed_0002_initial'),
        ('MediaList', '0007_delete_mediabyactor_alter_media_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='media',
        ),
        migrations.AddField(
            model_name='list',
            name='media',
            field=models.ManyToManyField(to='MediaList.media'),
        ),
    ]
