# Generated by Django 5.2 on 2025-05-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media_cover/'),
        ),
    ]
