# Generated by Django 5.2 on 2025-05-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaList', '0001_initial_squashed_0002_alter_media_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaByActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.JSONField(max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('classification', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=125)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media_cover/')),
            ],
            options={
                'db_table': 'vw_media_actors',
                'managed': False,
            },
        ),
    ]
