# Generated by Django 5.2 on 2025-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaList', '0003_mediabyactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='mediaproduction',
            name='actor',
        ),
        migrations.AddField(
            model_name='mediaproduction',
            name='actor',
            field=models.ManyToManyField(to='MediaList.actor'),
        ),
    ]
