# Generated by Django 5.2 on 2025-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaList', '0004_actor_remove_mediaproduction_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaproduction',
            name='actor',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.AddField(
            model_name='mediaproduction',
            name='actor',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
