# Generated by Django 5.2 on 2025-05-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaList', '0005_remove_mediaproduction_actor_delete_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
