# Generated by Django 5.2 on 2025-05-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaList', '0006_alter_media_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaByActor',
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='mediacategory',
            options={'verbose_name': 'Media Category'},
        ),
        migrations.AlterModelOptions(
            name='mediaproduction',
            options={'verbose_name': 'Media Production'},
        ),
    ]
