# Generated by Django 5.2 on 2025-05-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('Reviews', '0001_initial'), ('Reviews', '0002_initial'), ('Reviews', '0003_alter_review_options'), ('Reviews', '0004_alter_review_options')]

    dependencies = [
        ('MediaList', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MediaList.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media', 'rate')},
            },
        ),
    ]
