# Generated by Django 5.2 on 2025-05-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': ' Avaliações'},
        ),
    ]
