# Generated by Django 5.2 on 2025-05-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
